"""Initial migration.

Revision ID: 894ba007d5f5
Revises: e96865e4fa62
Create Date: 2022-05-06 05:37:52.942146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894ba007d5f5'
down_revision = 'e96865e4fa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('e', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('f', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('scorea', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('scoreb', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('scorec', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('scored', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('scoree', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('scoref', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'scoref')
    op.drop_column('questions', 'scoree')
    op.drop_column('questions', 'scored')
    op.drop_column('questions', 'scorec')
    op.drop_column('questions', 'scoreb')
    op.drop_column('questions', 'scorea')
    op.drop_column('questions', 'f')
    op.drop_column('questions', 'e')
    # ### end Alembic commands ###
